extends: airbnb-base
env:
  node: true
plugins:
  - import
rules:
  global-require: off
  import/no-dynamic-require: off
  no-param-reassign: off
  consistent-return: off
  guard-for-in: off
  no-restricted-syntax: off
