extends: airbnb-base
env:
  node: true
plugins:
  - import
rules:
  global-require: off
  import/no-dynamic-require: off
  no-param-reassign: off
  consistent-return: off
  guard-for-in: off
  no-restricted-syntax: off
  camelcase: off
  no-undef: off
  default-case: off
  no-underscore-dangle: off
