language: node_js

services:
  - mongodb

node_js:
  - 6
  - 7

cache: yarn

install:
  - npm install

before_script:
  - npm link

script:
  - npm run eslint
  - apogeu new my-project --debug
  - cd my-project
  - apogeu test unit
  - apogeu test integration
